/**PERFIL DA CARTEIRA */

export const CLIENTES_ATIVOS_CHART = 'CLIENTES_ATIVOS_CHART';

export const CLIENTES_IMPORTADOR_EXPORTADOR = 'CLIENTES_IMPORTADOR_EXPORTADOR';
export const SEGMENTO_CLIENTE = 'SEGMENTO_CLIENTE';
export const SEGMENTO_ECONOMICO = 'SEGMENTO_ECONOMICO';
export const LIMITE_DE_CREDITO = 'LIMITE_DE_CREDITO';
